"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def is_even(n):
    if n%2 ==0:
        return True
    else:
        return False

def fibonacci():
    even_sequence = [2]
    sequence = [1, 2]
    i = 0
    while sequence[i+1] < 4000000:
        fib1 = sequence[i]
        fib2 = sequence[i+1]
        sequence.append(fib1+fib2)
        if is_even(fib1+fib2):
            even_sequence.append(fib1+fib2)
        i += 1
    return sum(even_sequence)

if __name__ == '__main__':
    print(fibonacci())